### ISSUE TITLE
lägg till mig som collaborator tror inte jag kan pusha något tills dess

### ISSUE THREAD

**Issue by bangobongo** [SnakiestCarrot/IV1350-sem3#2]
Bee Movie قصة نحلة تخرج للتو من الجامعة ، يخيب أمله لأن مستقبله وعمله الوحيد هو صنع العسل. لكن في 2007، خلال رحلة خاصة خارج خليته، أنقذت فانيسا حياته، وهي بائعة زهور في مدينة نيويورك. تزدهر العلاقة بينهما، يكتشف بعدها باري بأن البشر يأكلون العسل، ويقرر بعد ذلك رفع دعوة قضائية على البشر.

**Comment by SnakiestCarrot** [comment]
Hahahahhahaa

**Comment by SnakiestCarrot** [comment]
Bruh
